### ISSUE TITLE
KeyError when processing AAPM Myo Dataset

### ISSUE THREAD

**Issue by Masaaki-75** [faebstn96/helix2fan#6]
I had all necessary packages installed, and tried running this on AAPM-Myo LDCT dataset (concretely on a single subject L109, containing multiple `.dcm` files), only to get the following error:

```bash
Processing scan scan_001.
Loading projection data: 100%|█████████████████████████████████████████████████| 4000/4000 [00:05<00:00, 750.04it/s]
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    run(parser)
  File "main.py", line 18, in run
    raw_projections, parser = read_dicom(parser)
  File "/home/clma/projects/helix2fan-master/read_data.py", line 96, in read_dicom
    hu_factor = float(data_headers[0][0x70411001].value)  # WaterAttenuationCoefficient (see manual for HU conversion)
  File "/home/clma/miniconda3/envs/recon38/lib/python3.8/site-packages/pydicom/dataset.py", line 987, in __getitem__
    elem = self._dict[tag]
KeyError: (7041, 1001)
```

Any advice on that?

**Comment by faebstn96** [comment]
Hi @Masaaki-75,
I am not sure which scan you are using because L109 does not exist in the current version of the data set. However, I also just recognized that they recently uploaded new scans, in particular scans from GE scanners. I developed the rebinning code mostly on Siemens scans (a few months back there were only Siemens scans available) which caused some problems in another issue #5  with some head scans already. Although the data set uses a standardized dicom header, it seems that some header entries are missing in some scans. Can you please try using the Siemens scans from the AAPM data set for now (there are around 50 abdomen scans that should work)? When selecting the data for downloading the "manufacturer" is listed.

If you still want to use the scan that did not work, you can try extracting the WaterAttenuationCoefficient entry from that dicom header (if there is any). Unfortunately, this might require some trial and error.

Hope that helped!
